version: '3.8'

services:
  taskrr_pg:
    image: postgres:15.1
    container_name: taskrr_pg
    restart: always
    environment:
      POSTGRES_USER: user_root
      POSTGRES_PASSWORD: 1234Admin
      POSTGRES_DB: taskrr
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
